package gui;

public class CourseCreation extends javax.swing.JFrame {

    public CourseCreation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chooseDateLabel = new javax.swing.JLabel();
        weekComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        suggestionList = new javax.swing.JList<>();
        expLabel2 = new javax.swing.JLabel();
        showCraftSuggestsButton = new javax.swing.JButton();
        startDateLabel = new javax.swing.JLabel();
        startDateField = new javax.swing.JTextField();
        finishDateLabel = new javax.swing.JLabel();
        choosenCraftLabel = new javax.swing.JLabel();
        choosenCraftField = new javax.swing.JTextField();
        showSuggestsButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        suggestionTable = new javax.swing.JTable();
        addToCourseButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        courseDetailsTable = new javax.swing.JTable();
        expLabel6 = new javax.swing.JLabel();
        feeField = new javax.swing.JTextField();
        feeLabel = new javax.swing.JLabel();
        feeLabel2 = new javax.swing.JLabel();
        saveCourseButton = new javax.swing.JButton();
        finishDateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        chooseDateLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        chooseDateLabel.setForeground(new java.awt.Color(51, 50, 44));
        chooseDateLabel.setText("Kurs zamanını seçiniz:");
        chooseDateLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        weekComboBox.setBackground(new java.awt.Color(153, 181, 155));
        weekComboBox.setForeground(new java.awt.Color(35, 39, 42));
        weekComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hafta içi", "Hafta sonu" }));

        suggestionList.setBackground(new java.awt.Color(153, 181, 155));
        suggestionList.setForeground(new java.awt.Color(35, 39, 42));
        suggestionList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(suggestionList);

        expLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        expLabel2.setForeground(new java.awt.Color(51, 50, 44));
        expLabel2.setText("Kursa eklenebilecekler dersler:");
        expLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        showCraftSuggestsButton.setBackground(new java.awt.Color(125, 218, 114));
        showCraftSuggestsButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        showCraftSuggestsButton.setForeground(new java.awt.Color(51, 50, 44));
        showCraftSuggestsButton.setText("⬇");
        showCraftSuggestsButton.setBorder(null);
        showCraftSuggestsButton.setBorderPainted(false);
        showCraftSuggestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCraftSuggestsButtonActionPerformed(evt);
            }
        });

        startDateLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        startDateLabel.setForeground(new java.awt.Color(51, 50, 44));
        startDateLabel.setText("Başlangıç Tarihi:");
        startDateLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        startDateField.setBackground(new java.awt.Color(249, 249, 249));
        startDateField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        startDateField.setForeground(new java.awt.Color(125, 218, 114));
        startDateField.setText("99.99.9999");
        startDateField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("LingWai TC", 0, 18), new java.awt.Color(51, 50, 44))); // NOI18N
        startDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateFieldActionPerformed(evt);
            }
        });

        finishDateLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        finishDateLabel.setForeground(new java.awt.Color(51, 50, 44));
        finishDateLabel.setText("Bitiş Tarihi:");
        finishDateLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        choosenCraftLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        choosenCraftLabel.setForeground(new java.awt.Color(51, 50, 44));
        choosenCraftLabel.setText("Seçilen Ders:");
        choosenCraftLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        choosenCraftField.setBackground(new java.awt.Color(249, 249, 249));
        choosenCraftField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        choosenCraftField.setForeground(new java.awt.Color(125, 218, 114));
        choosenCraftField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("LingWai TC", 0, 18), new java.awt.Color(51, 50, 44))); // NOI18N

        showSuggestsButton.setBackground(new java.awt.Color(125, 218, 114));
        showSuggestsButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        showSuggestsButton.setForeground(new java.awt.Color(51, 50, 44));
        showSuggestsButton.setText("⬇");
        showSuggestsButton.setBorder(null);
        showSuggestsButton.setBorderPainted(false);
        showSuggestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSuggestsButtonActionPerformed(evt);
            }
        });

        suggestionTable.setBackground(new java.awt.Color(153, 181, 155));
        suggestionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Öğretmen", "Gün", "Saat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(suggestionTable);

        addToCourseButton.setBackground(new java.awt.Color(125, 218, 114));
        addToCourseButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        addToCourseButton.setForeground(new java.awt.Color(51, 50, 44));
        addToCourseButton.setText("Kursa Ekle");
        addToCourseButton.setBorder(null);
        addToCourseButton.setBorderPainted(false);
        addToCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCourseButtonActionPerformed(evt);
            }
        });

        courseDetailsTable.setBackground(new java.awt.Color(153, 181, 155));
        courseDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ders", "Öğretmen", "Gün", "Saat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(courseDetailsTable);

        expLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        expLabel6.setForeground(new java.awt.Color(51, 50, 44));
        expLabel6.setText("Oluşturulan kurs:");
        expLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        feeField.setBackground(new java.awt.Color(249, 249, 249));
        feeField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        feeField.setForeground(new java.awt.Color(125, 218, 114));
        feeField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("LingWai TC", 0, 18), new java.awt.Color(51, 50, 44))); // NOI18N

        feeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        feeLabel.setForeground(new java.awt.Color(51, 50, 44));
        feeLabel.setText("Toplam Ücret:");
        feeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        feeLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        feeLabel2.setForeground(new java.awt.Color(51, 50, 44));
        feeLabel2.setText("TL");
        feeLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        saveCourseButton.setBackground(new java.awt.Color(125, 218, 114));
        saveCourseButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        saveCourseButton.setForeground(new java.awt.Color(51, 50, 44));
        saveCourseButton.setText("Kaydet");
        saveCourseButton.setBorder(null);
        saveCourseButton.setBorderPainted(false);
        saveCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCourseButtonActionPerformed(evt);
            }
        });

        finishDateField.setBackground(new java.awt.Color(249, 249, 249));
        finishDateField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        finishDateField.setForeground(new java.awt.Color(125, 218, 114));
        finishDateField.setText("99.99.9999");
        finishDateField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("LingWai TC", 0, 18), new java.awt.Color(51, 50, 44))); // NOI18N
        finishDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishDateFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addToCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(choosenCraftLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(choosenCraftField, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(showSuggestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(expLabel2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(chooseDateLabel)
                            .addGap(18, 18, 18)
                            .addComponent(weekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(showCraftSuggestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(startDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finishDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(finishDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(feeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(feeField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(feeLabel2))
                            .addComponent(saveCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseDateLabel)
                    .addComponent(weekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showCraftSuggestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateLabel)
                    .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finishDateLabel)
                    .addComponent(finishDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expLabel2)
                    .addComponent(expLabel6))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(choosenCraftLabel)
                            .addComponent(choosenCraftField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showSuggestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(feeLabel)
                            .addComponent(feeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(feeLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addToCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showCraftSuggestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCraftSuggestsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showCraftSuggestsButtonActionPerformed

    private void showSuggestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSuggestsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showSuggestsButtonActionPerformed

    private void addToCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCourseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addToCourseButtonActionPerformed

    private void saveCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCourseButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_saveCourseButtonActionPerformed

    private void startDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateFieldActionPerformed

    private void finishDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finishDateFieldActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseCreation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCourseButton;
    private javax.swing.JLabel chooseDateLabel;
    private javax.swing.JTextField choosenCraftField;
    private javax.swing.JLabel choosenCraftLabel;
    private javax.swing.JTable courseDetailsTable;
    private javax.swing.JLabel expLabel2;
    private javax.swing.JLabel expLabel6;
    private javax.swing.JTextField feeField;
    private javax.swing.JLabel feeLabel;
    private javax.swing.JLabel feeLabel2;
    private javax.swing.JTextField finishDateField;
    private javax.swing.JLabel finishDateLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton saveCourseButton;
    private javax.swing.JButton showCraftSuggestsButton;
    private javax.swing.JButton showSuggestsButton;
    private javax.swing.JTextField startDateField;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JList<String> suggestionList;
    private javax.swing.JTable suggestionTable;
    private javax.swing.JComboBox<String> weekComboBox;
    // End of variables declaration//GEN-END:variables
}
