package gui;

import database.DatabaseHelper;
import javax.swing.JOptionPane;
import management.Craft;

public class Dashboard extends javax.swing.JFrame {
    
    public Dashboard() {
        initComponents();
        DatabaseHelper.displayAllCrafts(craftsTable);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dashboardPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        instructorOpPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        instructorsTable = new javax.swing.JTable();
        addInstructorButton = new javax.swing.JButton();
        deleteInstructorButton = new javax.swing.JButton();
        updateInstructorButton = new javax.swing.JButton();
        addInstructorDetailsButton = new javax.swing.JButton();
        showScheduleButton = new javax.swing.JButton();
        lessonOpPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        craftsTable = new javax.swing.JTable();
        addCraftButton = new javax.swing.JButton();
        updateCraftButton = new javax.swing.JButton();
        deleteCraftButton = new javax.swing.JButton();
        studentOpPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        addStudentButton = new javax.swing.JButton();
        showNewCoursesButton = new javax.swing.JButton();
        deleteStudentButton = new javax.swing.JButton();
        updateStudentButton = new javax.swing.JButton();
        showOldCoursesButton = new javax.swing.JButton();
        courseOpPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        coursesTable1 = new javax.swing.JTable();
        addCourseButton = new javax.swing.JButton();
        deleteCourseButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        salesPanel = new javax.swing.JPanel();
        chooseDateLabel = new javax.swing.JLabel();
        weekComboBox = new javax.swing.JComboBox<>();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        showNameButton = new javax.swing.JButton();
        nameSurnameLabel = new javax.swing.JLabel();
        nameSurnameField = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        choosenCraftList = new javax.swing.JList<>();
        expLabel1 = new javax.swing.JLabel();
        maxBudgetLabel = new javax.swing.JLabel();
        budgetField = new javax.swing.JTextField();
        feeLabel2 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        coursesTable2 = new javax.swing.JTable();
        paymentButton = new javax.swing.JButton();
        cashRadioButton = new javax.swing.JRadioButton();
        cardRadioButton = new javax.swing.JRadioButton();
        expLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dashboardPanel.setBackground(new java.awt.Color(153, 181, 155));

        jTabbedPane1.setBackground(new java.awt.Color(51, 50, 44));
        jTabbedPane1.setForeground(new java.awt.Color(249, 249, 249));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setRequestFocusEnabled(false);

        instructorOpPanel.setBackground(new java.awt.Color(249, 249, 249));

        instructorsTable.setBackground(new java.awt.Color(153, 181, 155));
        instructorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ad Soyad", "E-Posta", "Cep Telefonu", "Ev Telefonu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(instructorsTable);
        if (instructorsTable.getColumnModel().getColumnCount() > 0) {
            instructorsTable.getColumnModel().getColumn(4).setResizable(false);
        }

        addInstructorButton.setBackground(new java.awt.Color(125, 218, 114));
        addInstructorButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        addInstructorButton.setForeground(new java.awt.Color(35, 39, 42));
        addInstructorButton.setText("Yeni Kayıt");
        addInstructorButton.setBorder(null);
        addInstructorButton.setBorderPainted(false);
        addInstructorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInstructorButtonActionPerformed(evt);
            }
        });

        deleteInstructorButton.setBackground(new java.awt.Color(153, 181, 155));
        deleteInstructorButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteInstructorButton.setForeground(new java.awt.Color(35, 39, 42));
        deleteInstructorButton.setText("Kayıt Sil");
        deleteInstructorButton.setBorder(null);
        deleteInstructorButton.setBorderPainted(false);
        deleteInstructorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInstructorButtonActionPerformed(evt);
            }
        });

        updateInstructorButton.setBackground(new java.awt.Color(153, 181, 155));
        updateInstructorButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        updateInstructorButton.setForeground(new java.awt.Color(35, 39, 42));
        updateInstructorButton.setText("Kayıt Güncelle");
        updateInstructorButton.setBorder(null);
        updateInstructorButton.setBorderPainted(false);
        updateInstructorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInstructorButtonActionPerformed(evt);
            }
        });

        addInstructorDetailsButton.setBackground(new java.awt.Color(153, 181, 155));
        addInstructorDetailsButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        addInstructorDetailsButton.setForeground(new java.awt.Color(35, 39, 42));
        addInstructorDetailsButton.setText("Detay Ekle");
        addInstructorDetailsButton.setBorder(null);
        addInstructorDetailsButton.setBorderPainted(false);
        addInstructorDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInstructorDetailsButtonActionPerformed(evt);
            }
        });

        showScheduleButton.setBackground(new java.awt.Color(153, 181, 155));
        showScheduleButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        showScheduleButton.setForeground(new java.awt.Color(35, 39, 42));
        showScheduleButton.setText("Ders Programı");
        showScheduleButton.setBorder(null);
        showScheduleButton.setBorderPainted(false);
        showScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showScheduleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout instructorOpPanelLayout = new javax.swing.GroupLayout(instructorOpPanel);
        instructorOpPanel.setLayout(instructorOpPanelLayout);
        instructorOpPanelLayout.setHorizontalGroup(
            instructorOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instructorOpPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(instructorOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addInstructorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateInstructorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteInstructorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addInstructorDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showScheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        instructorOpPanelLayout.setVerticalGroup(
            instructorOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instructorOpPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(instructorOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(instructorOpPanelLayout.createSequentialGroup()
                        .addComponent(addInstructorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateInstructorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteInstructorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addInstructorDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showScheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ÖĞRETMEN İŞLEMLERİ", instructorOpPanel);

        lessonOpPanel.setBackground(new java.awt.Color(249, 249, 249));
        lessonOpPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        craftsTable.setBackground(new java.awt.Color(153, 181, 155));
        craftsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ders ID", "Ders Adı", "Açıklama", "Zaman", "Ücret"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(craftsTable);

        addCraftButton.setBackground(new java.awt.Color(125, 218, 114));
        addCraftButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        addCraftButton.setForeground(new java.awt.Color(35, 39, 42));
        addCraftButton.setText("Yeni Kayıt");
        addCraftButton.setBorder(null);
        addCraftButton.setBorderPainted(false);
        addCraftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCraftButtonActionPerformed(evt);
            }
        });

        updateCraftButton.setBackground(new java.awt.Color(153, 181, 155));
        updateCraftButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        updateCraftButton.setForeground(new java.awt.Color(35, 39, 42));
        updateCraftButton.setText("Kayıt Güncelle");
        updateCraftButton.setBorder(null);
        updateCraftButton.setBorderPainted(false);
        updateCraftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCraftButtonActionPerformed(evt);
            }
        });

        deleteCraftButton.setBackground(new java.awt.Color(153, 181, 155));
        deleteCraftButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteCraftButton.setForeground(new java.awt.Color(35, 39, 42));
        deleteCraftButton.setText("Kayıt Sil");
        deleteCraftButton.setBorder(null);
        deleteCraftButton.setBorderPainted(false);
        deleteCraftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCraftButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lessonOpPanelLayout = new javax.swing.GroupLayout(lessonOpPanel);
        lessonOpPanel.setLayout(lessonOpPanelLayout);
        lessonOpPanelLayout.setHorizontalGroup(
            lessonOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lessonOpPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(lessonOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateCraftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCraftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCraftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        lessonOpPanelLayout.setVerticalGroup(
            lessonOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lessonOpPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(lessonOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lessonOpPanelLayout.createSequentialGroup()
                        .addComponent(addCraftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateCraftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteCraftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DERS İŞLEMLERİ", lessonOpPanel);

        studentOpPanel.setBackground(new java.awt.Color(249, 249, 249));

        studentsTable.setBackground(new java.awt.Color(153, 181, 155));
        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ad Soyad", "E-Posta", "Cep Telefonu", "Ev Telefonu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentsTable);
        if (studentsTable.getColumnModel().getColumnCount() > 0) {
            studentsTable.getColumnModel().getColumn(4).setResizable(false);
        }

        addStudentButton.setBackground(new java.awt.Color(125, 218, 114));
        addStudentButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        addStudentButton.setForeground(new java.awt.Color(35, 39, 42));
        addStudentButton.setText("Yeni Kayıt");
        addStudentButton.setBorder(null);
        addStudentButton.setBorderPainted(false);
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        showNewCoursesButton.setBackground(new java.awt.Color(153, 181, 155));
        showNewCoursesButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        showNewCoursesButton.setForeground(new java.awt.Color(35, 39, 42));
        showNewCoursesButton.setText("Güncel Kursları Görüntüle");
        showNewCoursesButton.setBorder(null);
        showNewCoursesButton.setBorderPainted(false);
        showNewCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showNewCoursesButtonActionPerformed(evt);
            }
        });

        deleteStudentButton.setBackground(new java.awt.Color(153, 181, 155));
        deleteStudentButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteStudentButton.setForeground(new java.awt.Color(35, 39, 42));
        deleteStudentButton.setText("Kayıt Sil");
        deleteStudentButton.setBorder(null);
        deleteStudentButton.setBorderPainted(false);
        deleteStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentButtonActionPerformed(evt);
            }
        });

        updateStudentButton.setBackground(new java.awt.Color(153, 181, 155));
        updateStudentButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        updateStudentButton.setForeground(new java.awt.Color(35, 39, 42));
        updateStudentButton.setText("Kayıt Güncelle");
        updateStudentButton.setBorder(null);
        updateStudentButton.setBorderPainted(false);
        updateStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentButtonActionPerformed(evt);
            }
        });

        showOldCoursesButton.setBackground(new java.awt.Color(153, 181, 155));
        showOldCoursesButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        showOldCoursesButton.setForeground(new java.awt.Color(35, 39, 42));
        showOldCoursesButton.setText("Geçmiş Kursları Görüntüle");
        showOldCoursesButton.setBorder(null);
        showOldCoursesButton.setBorderPainted(false);
        showOldCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOldCoursesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentOpPanelLayout = new javax.swing.GroupLayout(studentOpPanel);
        studentOpPanel.setLayout(studentOpPanelLayout);
        studentOpPanelLayout.setHorizontalGroup(
            studentOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentOpPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addGroup(studentOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showNewCoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showOldCoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        studentOpPanelLayout.setVerticalGroup(
            studentOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentOpPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(studentOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentOpPanelLayout.createSequentialGroup()
                        .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showNewCoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showOldCoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("KURSİYER İŞLEMLERİ", studentOpPanel);

        courseOpPanel.setBackground(new java.awt.Color(249, 249, 249));

        coursesTable1.setBackground(new java.awt.Color(153, 181, 155));
        coursesTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kurs ID", "Ders Adı", "Kurs Zamanı", "Kurs Ücreti"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(coursesTable1);

        addCourseButton.setBackground(new java.awt.Color(125, 218, 114));
        addCourseButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        addCourseButton.setForeground(new java.awt.Color(35, 39, 42));
        addCourseButton.setText("Kurs Oluştur");
        addCourseButton.setBorder(null);
        addCourseButton.setBorderPainted(false);

        deleteCourseButton.setBackground(new java.awt.Color(153, 181, 155));
        deleteCourseButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteCourseButton.setForeground(new java.awt.Color(35, 39, 42));
        deleteCourseButton.setText("Kayıt Sil");
        deleteCourseButton.setBorder(null);
        deleteCourseButton.setBorderPainted(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("buraya kurs secince kurs icindeki\ndersleri ve ogretmenleri gosterme\nbutonu falan ekleyebiliriz ama \nsimdilik kalsin acil degil\n");
        jScrollPane6.setViewportView(jTextArea1);

        javax.swing.GroupLayout courseOpPanelLayout = new javax.swing.GroupLayout(courseOpPanel);
        courseOpPanel.setLayout(courseOpPanelLayout);
        courseOpPanelLayout.setHorizontalGroup(
            courseOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseOpPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addGroup(courseOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(courseOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(deleteCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        courseOpPanelLayout.setVerticalGroup(
            courseOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseOpPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(courseOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(courseOpPanelLayout.createSequentialGroup()
                        .addComponent(addCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("KURS İŞLEMLERİ", courseOpPanel);

        salesPanel.setBackground(new java.awt.Color(249, 249, 249));

        chooseDateLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        chooseDateLabel.setForeground(new java.awt.Color(51, 50, 44));
        chooseDateLabel.setText("Kurs zamanını seçiniz:");
        chooseDateLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        weekComboBox.setBackground(new java.awt.Color(153, 181, 155));
        weekComboBox.setForeground(new java.awt.Color(35, 39, 42));
        weekComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hafta içi", "Hafta sonu" }));

        emailLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(51, 50, 44));
        emailLabel.setText("Kursiyerin E-postası:");
        emailLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        emailField.setBackground(new java.awt.Color(249, 249, 249));
        emailField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        emailField.setForeground(new java.awt.Color(125, 218, 114));
        emailField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("LingWai TC", 0, 18), new java.awt.Color(51, 50, 44))); // NOI18N

        showNameButton.setBackground(new java.awt.Color(125, 218, 114));
        showNameButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        showNameButton.setForeground(new java.awt.Color(51, 50, 44));
        showNameButton.setText("⬇");
        showNameButton.setBorder(null);
        showNameButton.setBorderPainted(false);

        nameSurnameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nameSurnameLabel.setForeground(new java.awt.Color(51, 50, 44));
        nameSurnameLabel.setText("Adı Soyadı:");
        nameSurnameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nameSurnameField.setBackground(new java.awt.Color(249, 249, 249));
        nameSurnameField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nameSurnameField.setForeground(new java.awt.Color(125, 218, 114));
        nameSurnameField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("LingWai TC", 0, 18), new java.awt.Color(51, 50, 44))); // NOI18N

        choosenCraftList.setBackground(new java.awt.Color(153, 181, 155));
        choosenCraftList.setForeground(new java.awt.Color(35, 39, 42));
        choosenCraftList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(choosenCraftList);

        expLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        expLabel1.setForeground(new java.awt.Color(51, 50, 44));
        expLabel1.setText("Talep edilen el sanatları:");
        expLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        maxBudgetLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        maxBudgetLabel.setForeground(new java.awt.Color(51, 50, 44));
        maxBudgetLabel.setText("Maksimum Bütçe:");
        maxBudgetLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        budgetField.setBackground(new java.awt.Color(249, 249, 249));
        budgetField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        budgetField.setForeground(new java.awt.Color(125, 218, 114));
        budgetField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("LingWai TC", 0, 18), new java.awt.Color(51, 50, 44))); // NOI18N

        feeLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        feeLabel2.setForeground(new java.awt.Color(51, 50, 44));
        feeLabel2.setText("TL");
        feeLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        searchButton.setBackground(new java.awt.Color(125, 218, 114));
        searchButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        searchButton.setForeground(new java.awt.Color(51, 50, 44));
        searchButton.setText("Ara");
        searchButton.setBorder(null);
        searchButton.setBorderPainted(false);

        coursesTable2.setBackground(new java.awt.Color(153, 181, 155));
        coursesTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kurs ID", "Dersler", "Kurs Başlangıcı", "Kurs Bitişi", "Ücret"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(coursesTable2);

        paymentButton.setBackground(new java.awt.Color(125, 218, 114));
        paymentButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        paymentButton.setForeground(new java.awt.Color(51, 50, 44));
        paymentButton.setText("Ödeme Yap");
        paymentButton.setBorder(null);
        paymentButton.setBorderPainted(false);

        buttonGroup1.add(cashRadioButton);
        cashRadioButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cashRadioButton.setForeground(new java.awt.Color(51, 50, 44));
        cashRadioButton.setText("Nakit");

        buttonGroup1.add(cardRadioButton);
        cardRadioButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cardRadioButton.setForeground(new java.awt.Color(51, 50, 44));
        cardRadioButton.setText("Kredi Kartı");

        expLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        expLabel2.setForeground(new java.awt.Color(51, 50, 44));
        expLabel2.setText("Ödeme Yöntemi:");
        expLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout salesPanelLayout = new javax.swing.GroupLayout(salesPanel);
        salesPanel.setLayout(salesPanelLayout);
        salesPanelLayout.setHorizontalGroup(
            salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanelLayout.createSequentialGroup()
                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, salesPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(salesPanelLayout.createSequentialGroup()
                                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emailLabel)
                                    .addComponent(nameSurnameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(nameSurnameField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(salesPanelLayout.createSequentialGroup()
                                .addComponent(chooseDateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(weekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(expLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(salesPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(salesPanelLayout.createSequentialGroup()
                                .addComponent(maxBudgetLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(budgetField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(feeLabel2))
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47)
                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, salesPanelLayout.createSequentialGroup()
                        .addComponent(expLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cashRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(cardRadioButton)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        salesPanelLayout.setVerticalGroup(
            salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salesPanelLayout.createSequentialGroup()
                        .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameSurnameLabel)
                            .addComponent(nameSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chooseDateLabel)
                            .addComponent(weekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(expLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxBudgetLabel)
                    .addComponent(budgetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feeLabel2)
                    .addComponent(expLabel2)
                    .addComponent(cashRadioButton)
                    .addComponent(cardRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("SATIŞ İŞLEMLERİ", salesPanel);

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened
    
    private void addInstructorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInstructorButtonActionPerformed
        dispose();
        new Register().setVisible(true);
    }//GEN-LAST:event_addInstructorButtonActionPerformed
    
    private void updateInstructorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInstructorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateInstructorButtonActionPerformed
    
    private void deleteInstructorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInstructorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteInstructorButtonActionPerformed
    
    private void addInstructorDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInstructorDetailsButtonActionPerformed
        dispose();
        new InstructorDetails().setVisible(true);
    }//GEN-LAST:event_addInstructorDetailsButtonActionPerformed
    
    private void showScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showScheduleButtonActionPerformed
        dispose();
        new Schedule().setVisible(true);
    }//GEN-LAST:event_showScheduleButtonActionPerformed
    
    private void addCraftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCraftButtonActionPerformed
        dispose();
        new CraftCreation().setVisible(true);
    }//GEN-LAST:event_addCraftButtonActionPerformed
    
    private void updateCraftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCraftButtonActionPerformed
        int selectedRow = craftsTable.getSelectedRow();
        int craftID = (int) craftsTable.getModel().getValueAt(selectedRow, 0);
        String tmpIsWeekday = (String) craftsTable.getModel().getValueAt(selectedRow, 3);
        double fee = (double) craftsTable.getModel().getValueAt(selectedRow, 4);
        System.out.println(fee);

        Craft.update(craftID, tmpIsWeekday, fee);
    }//GEN-LAST:event_updateCraftButtonActionPerformed
    
    private void deleteCraftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCraftButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCraftButtonActionPerformed
    
    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        dispose();
        new Register().setVisible(true);
    }//GEN-LAST:event_addStudentButtonActionPerformed
    
    private void updateStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateStudentButtonActionPerformed
    
    private void deleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteStudentButtonActionPerformed
    
    private void showNewCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showNewCoursesButtonActionPerformed
        dispose();
        new StudentCourses().setVisible(true);
    }//GEN-LAST:event_showNewCoursesButtonActionPerformed
    
    private void showOldCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOldCoursesButtonActionPerformed
        dispose();
        new StudentCourses().setVisible(true);
    }//GEN-LAST:event_showOldCoursesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseButton;
    private javax.swing.JButton addCraftButton;
    private javax.swing.JButton addInstructorButton;
    private javax.swing.JButton addInstructorDetailsButton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JTextField budgetField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cardRadioButton;
    private javax.swing.JRadioButton cashRadioButton;
    private javax.swing.JLabel chooseDateLabel;
    private javax.swing.JList<String> choosenCraftList;
    private javax.swing.JPanel courseOpPanel;
    private javax.swing.JTable coursesTable1;
    private javax.swing.JTable coursesTable2;
    private javax.swing.JTable craftsTable;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JButton deleteCourseButton;
    private javax.swing.JButton deleteCraftButton;
    private javax.swing.JButton deleteInstructorButton;
    private javax.swing.JButton deleteStudentButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel expLabel1;
    private javax.swing.JLabel expLabel2;
    private javax.swing.JLabel feeLabel2;
    private javax.swing.JPanel instructorOpPanel;
    private javax.swing.JTable instructorsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel lessonOpPanel;
    private javax.swing.JLabel maxBudgetLabel;
    private javax.swing.JTextField nameSurnameField;
    private javax.swing.JLabel nameSurnameLabel;
    private javax.swing.JButton paymentButton;
    private javax.swing.JPanel salesPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton showNameButton;
    private javax.swing.JButton showNewCoursesButton;
    private javax.swing.JButton showOldCoursesButton;
    private javax.swing.JButton showScheduleButton;
    private javax.swing.JPanel studentOpPanel;
    private javax.swing.JTable studentsTable;
    private javax.swing.JButton updateCraftButton;
    private javax.swing.JButton updateInstructorButton;
    private javax.swing.JButton updateStudentButton;
    private javax.swing.JComboBox<String> weekComboBox;
    // End of variables declaration//GEN-END:variables
}
