package craftcourses;
import javax.swing.*;
import java.awt.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author busramgural
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        teacherOpPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        teachersTable = new javax.swing.JTable();
        addTeacherButton = new javax.swing.JButton();
        deleteTeacherButton = new javax.swing.JButton();
        updateTeacherButton = new javax.swing.JButton();
        showLessonsButton = new javax.swing.JButton();
        deleteTeacherButton2 = new javax.swing.JButton();
        lessonOpPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        addLessonButton = new javax.swing.JButton();
        updateLessonButton = new javax.swing.JButton();
        deleteLessonButton = new javax.swing.JButton();
        traineeOpPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        traineesTable = new javax.swing.JTable();
        addTraineeButton = new javax.swing.JButton();
        showNewCoursesButton = new javax.swing.JButton();
        deleteTraineeButton = new javax.swing.JButton();
        updateTraineeButton = new javax.swing.JButton();
        showOldCoursesButton = new javax.swing.JButton();
        courseOpPanel = new javax.swing.JPanel();
        employeeOpPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        employeesTable = new javax.swing.JTable();
        addEmployeeButton = new javax.swing.JButton();
        updateEmployeeButton = new javax.swing.JButton();
        deleteEmployeeButton = new javax.swing.JButton();
        deleteEmployeeButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dashboardPanel.setBackground(new java.awt.Color(153, 181, 155));

        jTabbedPane1.setBackground(new java.awt.Color(51, 50, 44));
        jTabbedPane1.setForeground(new java.awt.Color(249, 249, 249));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setRequestFocusEnabled(false);

        teacherOpPanel.setBackground(new java.awt.Color(249, 249, 249));

        teachersTable.setBackground(new java.awt.Color(153, 181, 155));
        teachersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "mert kurnaz", "dfnkjdf", "87493857", "84759"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Ad Soyad", "E-Posta", "Cep Telefonu", "Ev Telefonu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(teachersTable);
        if (teachersTable.getColumnModel().getColumnCount() > 0) {
            teachersTable.getColumnModel().getColumn(4).setResizable(false);
            teachersTable.getColumnModel().getColumn(4).setHeaderValue("Ev Telefonu");
        }

        addTeacherButton.setBackground(new java.awt.Color(125, 218, 114));
        addTeacherButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        addTeacherButton.setForeground(new java.awt.Color(35, 39, 42));
        addTeacherButton.setText("Yeni Kayıt");
        addTeacherButton.setBorder(null);
        addTeacherButton.setBorderPainted(false);
        addTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherButtonActionPerformed(evt);
            }
        });

        deleteTeacherButton.setBackground(new java.awt.Color(153, 181, 155));
        deleteTeacherButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteTeacherButton.setForeground(new java.awt.Color(35, 39, 42));
        deleteTeacherButton.setText("Kayıt Sil");
        deleteTeacherButton.setBorder(null);
        deleteTeacherButton.setBorderPainted(false);
        deleteTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTeacherButtonActionPerformed(evt);
            }
        });

        updateTeacherButton.setBackground(new java.awt.Color(153, 181, 155));
        updateTeacherButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        updateTeacherButton.setForeground(new java.awt.Color(35, 39, 42));
        updateTeacherButton.setText("Kayıt Güncelle");
        updateTeacherButton.setBorder(null);
        updateTeacherButton.setBorderPainted(false);
        updateTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTeacherButtonActionPerformed(evt);
            }
        });

        showLessonsButton.setBackground(new java.awt.Color(153, 181, 155));
        showLessonsButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        showLessonsButton.setForeground(new java.awt.Color(35, 39, 42));
        showLessonsButton.setText("Branşlar");
        showLessonsButton.setBorder(null);
        showLessonsButton.setBorderPainted(false);
        showLessonsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLessonsButtonActionPerformed(evt);
            }
        });

        deleteTeacherButton2.setBackground(new java.awt.Color(153, 181, 155));
        deleteTeacherButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteTeacherButton2.setForeground(new java.awt.Color(35, 39, 42));
        deleteTeacherButton2.setText("Ders Programı");
        deleteTeacherButton2.setBorder(null);
        deleteTeacherButton2.setBorderPainted(false);
        deleteTeacherButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTeacherButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout teacherOpPanelLayout = new javax.swing.GroupLayout(teacherOpPanel);
        teacherOpPanel.setLayout(teacherOpPanelLayout);
        teacherOpPanelLayout.setHorizontalGroup(
            teacherOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherOpPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(teacherOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showLessonsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteTeacherButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );
        teacherOpPanelLayout.setVerticalGroup(
            teacherOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherOpPanelLayout.createSequentialGroup()
                .addGroup(teacherOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherOpPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(teacherOpPanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(addTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showLessonsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteTeacherButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ÖĞRETMEN İŞLEMLERİ", teacherOpPanel);

        lessonOpPanel.setBackground(new java.awt.Color(249, 249, 249));
        lessonOpPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        lessonsTable.setBackground(new java.awt.Color(153, 181, 155));
        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "mert kurnaz", "dfnkjdf", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ders ID", "Ders Adı", "Ders Günü", "Ders Ücreti"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(lessonsTable);

        addLessonButton.setBackground(new java.awt.Color(125, 218, 114));
        addLessonButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        addLessonButton.setForeground(new java.awt.Color(35, 39, 42));
        addLessonButton.setText("Yeni Kayıt");
        addLessonButton.setBorder(null);
        addLessonButton.setBorderPainted(false);
        addLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonButtonActionPerformed(evt);
            }
        });

        updateLessonButton.setBackground(new java.awt.Color(153, 181, 155));
        updateLessonButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        updateLessonButton.setForeground(new java.awt.Color(35, 39, 42));
        updateLessonButton.setText("Kayıt Güncelle");
        updateLessonButton.setBorder(null);
        updateLessonButton.setBorderPainted(false);
        updateLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLessonButtonActionPerformed(evt);
            }
        });

        deleteLessonButton.setBackground(new java.awt.Color(153, 181, 155));
        deleteLessonButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteLessonButton.setForeground(new java.awt.Color(35, 39, 42));
        deleteLessonButton.setText("Kayıt Sil");
        deleteLessonButton.setBorder(null);
        deleteLessonButton.setBorderPainted(false);
        deleteLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLessonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lessonOpPanelLayout = new javax.swing.GroupLayout(lessonOpPanel);
        lessonOpPanel.setLayout(lessonOpPanelLayout);
        lessonOpPanelLayout.setHorizontalGroup(
            lessonOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lessonOpPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(lessonOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        lessonOpPanelLayout.setVerticalGroup(
            lessonOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lessonOpPanelLayout.createSequentialGroup()
                .addGroup(lessonOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lessonOpPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lessonOpPanelLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(addLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DERS İŞLEMLERİ", lessonOpPanel);

        traineeOpPanel.setBackground(new java.awt.Color(249, 249, 249));

        traineesTable.setBackground(new java.awt.Color(153, 181, 155));
        traineesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "mert kurnaz", "dfnkjdf", "87493857", "84759"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Ad Soyad", "E-Posta", "Cep Telefonu", "Ev Telefonu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(traineesTable);
        if (traineesTable.getColumnModel().getColumnCount() > 0) {
            traineesTable.getColumnModel().getColumn(4).setResizable(false);
            traineesTable.getColumnModel().getColumn(4).setHeaderValue("Ev Telefonu");
        }

        addTraineeButton.setBackground(new java.awt.Color(125, 218, 114));
        addTraineeButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        addTraineeButton.setForeground(new java.awt.Color(35, 39, 42));
        addTraineeButton.setText("Yeni Kayıt");
        addTraineeButton.setBorder(null);
        addTraineeButton.setBorderPainted(false);
        addTraineeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTraineeButtonActionPerformed(evt);
            }
        });

        showNewCoursesButton.setBackground(new java.awt.Color(153, 181, 155));
        showNewCoursesButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        showNewCoursesButton.setForeground(new java.awt.Color(35, 39, 42));
        showNewCoursesButton.setText("Güncel Kursları Görüntüle");
        showNewCoursesButton.setBorder(null);
        showNewCoursesButton.setBorderPainted(false);
        showNewCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showNewCoursesButtonActionPerformed(evt);
            }
        });

        deleteTraineeButton.setBackground(new java.awt.Color(153, 181, 155));
        deleteTraineeButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteTraineeButton.setForeground(new java.awt.Color(35, 39, 42));
        deleteTraineeButton.setText("Kayıt Sil");
        deleteTraineeButton.setBorder(null);
        deleteTraineeButton.setBorderPainted(false);
        deleteTraineeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTraineeButtonActionPerformed(evt);
            }
        });

        updateTraineeButton.setBackground(new java.awt.Color(153, 181, 155));
        updateTraineeButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        updateTraineeButton.setForeground(new java.awt.Color(35, 39, 42));
        updateTraineeButton.setText("Kayıt Güncelle");
        updateTraineeButton.setBorder(null);
        updateTraineeButton.setBorderPainted(false);
        updateTraineeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTraineeButtonActionPerformed(evt);
            }
        });

        showOldCoursesButton.setBackground(new java.awt.Color(153, 181, 155));
        showOldCoursesButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        showOldCoursesButton.setForeground(new java.awt.Color(35, 39, 42));
        showOldCoursesButton.setText("Geçmiş Kursları Görüntüle");
        showOldCoursesButton.setBorder(null);
        showOldCoursesButton.setBorderPainted(false);
        showOldCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOldCoursesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout traineeOpPanelLayout = new javax.swing.GroupLayout(traineeOpPanel);
        traineeOpPanel.setLayout(traineeOpPanelLayout);
        traineeOpPanelLayout.setHorizontalGroup(
            traineeOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, traineeOpPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(traineeOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTraineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showNewCoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateTraineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteTraineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showOldCoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );
        traineeOpPanelLayout.setVerticalGroup(
            traineeOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(traineeOpPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, traineeOpPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTraineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateTraineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteTraineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showNewCoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showOldCoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        jTabbedPane1.addTab("KURSİYER İŞLEMLERİ", traineeOpPanel);

        courseOpPanel.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout courseOpPanelLayout = new javax.swing.GroupLayout(courseOpPanel);
        courseOpPanel.setLayout(courseOpPanelLayout);
        courseOpPanelLayout.setHorizontalGroup(
            courseOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        courseOpPanelLayout.setVerticalGroup(
            courseOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("KURS İŞLEMLERİ", courseOpPanel);

        employeeOpPanel.setBackground(new java.awt.Color(249, 249, 249));

        employeesTable.setBackground(new java.awt.Color(153, 181, 155));
        employeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "mert kurnaz", "dfnkjdf", "87493857"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Ad Soyad", "E-Posta", "Cep Telefonu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(employeesTable);

        addEmployeeButton.setBackground(new java.awt.Color(125, 218, 114));
        addEmployeeButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        addEmployeeButton.setForeground(new java.awt.Color(35, 39, 42));
        addEmployeeButton.setText("Yeni Kayıt");
        addEmployeeButton.setBorder(null);
        addEmployeeButton.setBorderPainted(false);
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });

        updateEmployeeButton.setBackground(new java.awt.Color(153, 181, 155));
        updateEmployeeButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        updateEmployeeButton.setForeground(new java.awt.Color(35, 39, 42));
        updateEmployeeButton.setText("Kayıt Güncelle");
        updateEmployeeButton.setBorder(null);
        updateEmployeeButton.setBorderPainted(false);
        updateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeButtonActionPerformed(evt);
            }
        });

        deleteEmployeeButton.setBackground(new java.awt.Color(153, 181, 155));
        deleteEmployeeButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteEmployeeButton.setForeground(new java.awt.Color(35, 39, 42));
        deleteEmployeeButton.setText("Kayıt Sil");
        deleteEmployeeButton.setBorder(null);
        deleteEmployeeButton.setBorderPainted(false);
        deleteEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeButtonActionPerformed(evt);
            }
        });

        deleteEmployeeButton1.setBackground(new java.awt.Color(153, 181, 155));
        deleteEmployeeButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteEmployeeButton1.setForeground(new java.awt.Color(35, 39, 42));
        deleteEmployeeButton1.setText("Çıkış Yap");
        deleteEmployeeButton1.setBorder(null);
        deleteEmployeeButton1.setBorderPainted(false);
        deleteEmployeeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout employeeOpPanelLayout = new javax.swing.GroupLayout(employeeOpPanel);
        employeeOpPanel.setLayout(employeeOpPanelLayout);
        employeeOpPanelLayout.setHorizontalGroup(
            employeeOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeOpPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(employeeOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEmployeeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
        );
        employeeOpPanelLayout.setVerticalGroup(
            employeeOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeOpPanelLayout.createSequentialGroup()
                .addGroup(employeeOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(employeeOpPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(employeeOpPanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteEmployeeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PERSONEL İŞLEMLERİ", employeeOpPanel);

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void addTraineeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTraineeButtonActionPerformed
        // TODO add your handling code here:
        new RegisterTrainee().setVisible(true);
    }//GEN-LAST:event_addTraineeButtonActionPerformed

    private void showNewCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showNewCoursesButtonActionPerformed
        // TODO add your handling code here:
        new TraineesCourses().setVisible(true);
    }//GEN-LAST:event_showNewCoursesButtonActionPerformed

    private void deleteTraineeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTraineeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTraineeButtonActionPerformed

    private void updateTraineeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTraineeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTraineeButtonActionPerformed

    private void showOldCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOldCoursesButtonActionPerformed
        // TODO add your handling code here:
        new TraineesCourses().setVisible(true);
    }//GEN-LAST:event_showOldCoursesButtonActionPerformed

    private void addTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTeacherButtonActionPerformed

    private void deleteTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTeacherButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTeacherButtonActionPerformed

    private void updateTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTeacherButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTeacherButtonActionPerformed

    private void showLessonsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLessonsButtonActionPerformed
        // TODO add your handling code here:
        
        //buraya ogretmenin verebilecegi dersleri bir popup ile gostericez
        
    }//GEN-LAST:event_showLessonsButtonActionPerformed

    private void deleteTeacherButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTeacherButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTeacherButton2ActionPerformed

    private void addLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addLessonButtonActionPerformed

    private void updateLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLessonButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateLessonButtonActionPerformed

    private void deleteLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLessonButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteLessonButtonActionPerformed

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void updateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEmployeeButtonActionPerformed

    private void deleteEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEmployeeButtonActionPerformed

    private void deleteEmployeeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEmployeeButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JButton addLessonButton;
    private javax.swing.JButton addTeacherButton;
    private javax.swing.JButton addTraineeButton;
    private javax.swing.JPanel courseOpPanel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JButton deleteEmployeeButton;
    private javax.swing.JButton deleteEmployeeButton1;
    private javax.swing.JButton deleteLessonButton;
    private javax.swing.JButton deleteTeacherButton;
    private javax.swing.JButton deleteTeacherButton2;
    private javax.swing.JButton deleteTraineeButton;
    private javax.swing.JPanel employeeOpPanel;
    private javax.swing.JTable employeesTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel lessonOpPanel;
    private javax.swing.JTable lessonsTable;
    private javax.swing.JButton showLessonsButton;
    private javax.swing.JButton showNewCoursesButton;
    private javax.swing.JButton showOldCoursesButton;
    private javax.swing.JPanel teacherOpPanel;
    private javax.swing.JTable teachersTable;
    private javax.swing.JPanel traineeOpPanel;
    private javax.swing.JTable traineesTable;
    private javax.swing.JButton updateEmployeeButton;
    private javax.swing.JButton updateLessonButton;
    private javax.swing.JButton updateTeacherButton;
    private javax.swing.JButton updateTraineeButton;
    // End of variables declaration//GEN-END:variables
}
